### ISSUE TITLE
DailyCC doesn't work 

### ISSUE THREAD

**Issue by Garrett1Tolbert** [BLACC-Smith/blacc-smith#13]
This may have been when we merged the changes, but I'm assuming affirmations aren't working either. I published messages to both pub-sub topics and nothing was sent to Discord. Need to check the logs and do some investigation.

**Comment by DarrylBrooks97** [comment]
Looking into this now

**Comment by DarrylBrooks97** [comment]
The throw causes the code to stop at runtime but does not stop the server from requesting it. This causes the request to timeout. We may need to look into a different approach on how to handle errors

**Comment by DarrylBrooks97** [comment]
Per @jonathan-elize 

> "For affirmations and dailyCC, we don’t run the code until the “ready” handler for discord is activated. This handler only activates the first time the discord client is ready, so in subsequent calls to the endpoint the handler doesn’t run again. If the handler doesn’t run, those endpoints don’t call res.send() and after a minute that results in time out for that endpoint "
