### ISSUE TITLE
Weekly Affirmations

### ISSUE THREAD

**Issue by DarrylBrooks97** [BLACC-Smith/blacc-smith#3]
Process:
- Create new cloud function firebase
- Create list of weekly affirmations within firestore
- Set up Cloud Scheduler to run every Monday morning at 9:00am 
- Check to see if affirmation has already been published
- Send affirmation if it's not present
- Append to affirmation history

**Comment by Garrett1Tolbert** [comment]
@DarrylBrooks97 You don't have to make the check to see if an affirmation has been published because affirmations can be repeated.
